// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZxliFWT9_9P3tCUM7cj3a-rqglqzQVAw',
    appId: '1:115562076415:web:a939725b87750ed35214ca',
    messagingSenderId: '115562076415',
    projectId: 'test-project-9c03e',
    authDomain: 'test-project-9c03e.firebaseapp.com',
    storageBucket: 'test-project-9c03e.appspot.com',
    measurementId: 'G-KEZ0SQWFLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV08fbaFFuIasCMXY_EPJCcdzeiBoxl1o',
    appId: '1:115562076415:android:72a4c1a67893c3f55214ca',
    messagingSenderId: '115562076415',
    projectId: 'test-project-9c03e',
    storageBucket: 'test-project-9c03e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmk92i7y-PLgRlZ5b1lwUYisCJpobRo44',
    appId: '1:115562076415:ios:9fe233cc33761aae5214ca',
    messagingSenderId: '115562076415',
    projectId: 'test-project-9c03e',
    storageBucket: 'test-project-9c03e.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmk92i7y-PLgRlZ5b1lwUYisCJpobRo44',
    appId: '1:115562076415:ios:9fe233cc33761aae5214ca',
    messagingSenderId: '115562076415',
    projectId: 'test-project-9c03e',
    storageBucket: 'test-project-9c03e.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZxliFWT9_9P3tCUM7cj3a-rqglqzQVAw',
    appId: '1:115562076415:web:64196923f9d4412e5214ca',
    messagingSenderId: '115562076415',
    projectId: 'test-project-9c03e',
    authDomain: 'test-project-9c03e.firebaseapp.com',
    storageBucket: 'test-project-9c03e.appspot.com',
    measurementId: 'G-H205BDF8X3',
  );
}
